<?php

test('an older database upgrades to the current schema without losing data', function () {
    // A second connection with its own search_path, so the throwaway schema
    // never disturbs the live test connection.
    [$host, $port, $dbname, $user, $pass, $query] = db_settings();
    $dsn = sprintf('pgsql:host=%s;port=%s;dbname=%s', $host, $port, $dbname);
    $sslmode = $query['sslmode'] ?? env('DB_SSLMODE', '');
    if ($sslmode !== '') {
        $dsn .= ';sslmode=' . $sslmode;
    }
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);

    $schema = 'legacy_' . bin2hex(random_bytes(4));
    $pdo->exec("CREATE SCHEMA $schema");
    try {
        $pdo->exec("SET search_path TO $schema");

        // The shape an install had before currency, session_epoch and
        // recurring_source_id existed. The income table is deliberately absent,
        // so this also covers migrating a half-created database.
        $pdo->exec('CREATE TABLE users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(32) NOT NULL UNIQUE,
            email VARCHAR(191) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )');
        $pdo->exec("ALTER TABLE users ADD COLUMN notification_preferences TEXT DEFAULT '{}'");
        $pdo->exec('CREATE TABLE expense_categories (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            name VARCHAR(60) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )');
        $pdo->exec('CREATE TABLE expenses (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            category_id INTEGER NULL,
            amount NUMERIC(12,2) NOT NULL,
            expense_date DATE NOT NULL,
            description VARCHAR(255),
            is_recurring SMALLINT DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )');
        $pdo->exec("INSERT INTO users (username, email, password_hash, notification_preferences) VALUES ('maya', 'maya@example.test', 'x', '{\"reminders\":0,\"budget_alerts\":1}')");
        $pdo->exec("INSERT INTO expense_categories (user_id, name) VALUES (1, 'Food')");
        $pdo->exec("INSERT INTO expenses (user_id, category_id, amount, expense_date, description) VALUES (1, 1, 12.5, '2025-01-02', 'Lunch')");
        expect_same(0, schema_version($pdo), 'starts unversioned');

        migrate($pdo);
        migrate($pdo); // idempotent

        expect_same(SCHEMA_VERSION, schema_version($pdo));
        foreach (['currency', 'notification_preferences', 'session_epoch'] as $column) {
            expect_true(in_array($column, column_names($pdo, 'users'), true), "users.$column");
        }
        expect_true(in_array('recurring_source_id', column_names($pdo, 'expenses'), true));
        foreach (['login_attempts', 'password_resets', 'notifications', 'mail_queue'] as $table) {
            expect_true(table_exists($pdo, $table), "table $table");
        }
        expect_same('Lunch', $pdo->query('SELECT description FROM expenses')->fetchColumn());
        expect_same('USD', $pdo->query('SELECT currency FROM users')->fetchColumn());
        expect_false(notification_prefs($pdo->query('SELECT * FROM users')->fetchAll()[0])['upcoming_payments'], '1.x reminder choice is kept');
    } finally {
        $pdo->exec('SET search_path TO public');
        $pdo->exec("DROP SCHEMA $schema CASCADE");
    }
});

test('the live test database is at the current schema version', function () {
    expect_same(SCHEMA_VERSION, schema_version(db()));
});
